### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by DmitryEfimenko** [Jam3/angular-components-library#9]
After updating from 1.0.2 to 1.0.3 I started getting an error during the run-time (build is successful):
> ERROR TypeError: Object(...) is not a function
    at angular-youtube-player.js:164
    at Module../node_modules/angular-youtube-player/fesm5/angular-youtube-player.js (angular-youtube-player.js:166)

**Comment by neo** [comment]
Hi can you please share a codesandbox/stackblitz example of the bug? I tried but couldn't reproduce the Error you saw. And at the meantime, you could stay using 1.0.2 as it should be the same code.

**Comment by neo** [comment]
and thanks a lot for using it and reporting the bug! 🙏

**Comment by ghost** [comment]
I had same issue and was able to digg to this message, maybe it will help you fix this:

WARNING in ./node_modules/angular-youtube-player/fesm5/angular-youtube-player.js 151:57-75
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Going back to 1.0.2 fixed issue
